name: ❔ Ask Question
description: Ask a question about how to use something, or to understand why something isn't working as you expect it to.
labels: ["type: question"]
body:
  - type: markdown
    attributes:
      value: |
        ❤️ Thank you for contributing to the using of Tai-e.

        **❗ Please note:**
        To expedite our response to your report and ensure it receives appropriate priority, please **include a reproducible test case** or script if possible ([see an example of how to write a reproducible case](https://github.com/pascal-lab/Tai-e/compare/how-to-write-a-reproducible-case)).

  - type: textarea
    id: overall-description
    attributes:
      label: Overall Description
      description: Give a concise overview of the issue.
      placeholder: "Brief overview of the issue"
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: "What you expected to happen"
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Describe what is actually happening.
      placeholder: "What is actually happening"
    validations:
      required: true

  - type: textarea
    id: tai-e-arguments
    attributes:
      label: Tai-e Arguments
      description: |
        Please provide the running arguments of Tai-e.
        _Note:_ You can paste the `output/options.yml` and `output/tai-e-plan.yml` files into the placeholders below.
      value: |
        <details>
          <summary>Click here to see Tai-e Options</summary>
          <!-- Please leave one blank line below for enabling the code block rendering. -->

          ```yaml
          {{The content of 'output/options.yml' file}}
          ```
        </details>
        <details>
          <summary>Click here to see Tai-e Analysis Plan</summary>
          <!-- Please leave one blank line below for enabling the code block rendering. -->

          ```yaml
          {{The content of 'output/tai-e-plan.yml' file}}
          ```
        </details>
    validations:
      required: true

  - type: textarea
    id: tai-e-log
    attributes:
      label: Tai-e Log
      description: |
        Provide the Tai-e log output which contains important information, such as JVM/OS, Tai-e version (git commit).
        _Note:_ You can paste the `output/tai-e.log` file into the placeholder below. If it is too long, you can attach it as a file.
      value: |
        <details>
          <summary>Click here to see Tai-e Log</summary>
          <!-- Please leave one blank line below for enabling the code block rendering. -->

          ```
          {{The content of 'output/tai-e.log' file}}
          ```
        </details>
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: |
        Provide any additional information or context about the bug.
        Such as the complete analyzed program (and/or its `.tir`), the taint configuration (`taint-config.yml`), etc.
      placeholder: |
        Any other relevant information, e.g.,
          the complete analyzed program (and/or its `.tir`),
          the taint configuration (`taint-config.yml`),
          the code you modified/added in Tai-e,
          etc.
    validations:
      required: false
